



SELECT type,COUNT(1) num FROM CRM.ADDRESS GROUP BY type HAVING COUNT(1) >5


SELECT * FROM (
SELECT *,ROW_NUMBER()OVER(ORDER BY id) rownumber FROM CRM.ADDRESS 
)t
WHERE rownumber BETWEEN 1 AND 100

SELECT * FROM (
SELECT  * ,RANK()OVER(PARTITION BY area_no ORDER BY id) num FROM crm.ADDRESS 
)t
WHERE num <3